version: '3.5'
services:
  mysql:
    build: rdb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./rdb/mysql-data:/var/lib/mysql
      - ./rdb/conf.d:/etc/mysql/conf.d
      - ./rdb/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
        - "3306:3306"
  psql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sample
    ports:
      - "5432:5432"
    volumes:
      - ./rdb/psql-data:/var/lib/postgresql/data