version: '3.5'
services:
  rdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sample
    ports:
      - "5432:5432"
    volumes:
      - ./rdb/psql-data:/var/lib/postgresql/data